NEWTUPLE = ("apple", "pear")
# print(id(NEWTUPLE))
# print(type(NEWTUPLE))
# print(dir(NEWTUPLE))
# print(NEWTUPLE.count("apple"))
# print(NEWTUPLE.index("apple"))
NEWTUPLE = list(NEWTUPLE)
print(type(NEWTUPLE))
NEWTUPLE.append("cherry")
print(NEWTUPLE)
NEWTUPLE = tuple(NEWTUPLE)
print(type(NEWTUPLE))
print(NEWTUPLE)
